import { Product, ShelfLocation, Review, FaqItem, OrderRecord } from './types';

export const CATEGORIES = [
  { id: 'all', label: 'Весь мерч' },
  { id: 'stands', label: 'Акриловые стенды' },
  { id: 'keychains', label: 'Брелоки' },
  { id: 'stickers', label: 'Стикерпаки' },
  { id: 'pins', label: 'Значки' },
  { id: 'apparel', label: 'Одежда' },
  { id: 'prints', label: 'Открытки & Зины' },
] as const;

export const PRODUCTS: Product[] = [
  {
    id: 'fraiters-stand-crimson',
    name: 'Акриловый стенд «Crimson Requiem»',
    category: 'stands',
    categoryName: 'Акриловый стенд',
    price: 950,
    oldPrice: 1100,
    inStock: true,
    stockCount: 8,
    badge: 'Хит продаж',
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-red-950 via-neutral-900 to-black',
    description: 'Двусторонний акриловый стенд с ультрачеткой печатью. Защитная пленка с обеих сторон. Подставка с гравировкой и пазами для устойчивости.',
    size: '15.5 см в высоту, толщина 4 мм',
    material: 'Оптический прозрачный акрил (PMMA), лазерная резка',
    features: ['Двусторонняя УФ-печать высокого разрешения', 'Фирменная гравированная подставка', 'Защитные транспортировочные пленки', 'Коллекционный вкладыш'],
  },
  {
    id: 'fraiters-stand-shadow',
    name: 'Диорама «Shadow Protocol» (3 детали)',
    category: 'stands',
    categoryName: 'Акриловая диорама',
    price: 1350,
    inStock: true,
    stockCount: 4,
    badge: 'Лимитированный тираж',
    image: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-neutral-900 via-red-950 to-black',
    description: 'Многослойная сборная диорама: задник с неоновым городом, передний план с персонажем и напольная платформа с эффектом отражения.',
    size: '18 x 14 см в собранном виде',
    material: 'Многослойный акрил 4 мм, глянцевое покрытие',
    features: ['3 независимых акриловых элемента', 'Глубокий объемный эффект', 'Устойчивые тройные пазы', 'Номерная карточка автора'],
  },
  {
    id: 'fraiters-charm-holo',
    name: 'Голографический брелок «Abyss Walker»',
    category: 'keychains',
    categoryName: 'Брелок',
    price: 490,
    inStock: true,
    stockCount: 19,
    badge: 'Новинка',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-red-900 via-neutral-900 to-black',
    description: 'Акриловый брелок с радужным голографическим переливом (битое стекло). Металлическое крепление в форме звезды черного цвета.',
    size: '7.5 см + карабин 4 см',
    material: 'Акрил с голографической ламинацией, металлический карабин-звездочка',
    features: ['Голографический эффект «Битое стекло»', 'Карабин-звезда gunmetal', 'Стойкий к царапинам слой', 'Двусторонний арт'],
  },
  {
    id: 'fraiters-charm-epoxy',
    name: 'Эпоксидный брелок «Bloodline Rune»',
    category: 'keychains',
    categoryName: 'Брелок',
    price: 450,
    oldPrice: 500,
    inStock: true,
    stockCount: 12,
    image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-rose-950 via-neutral-950 to-black',
    description: 'Объемная эпоксидная линза с блестками внутри. Приятный тактильный купол, создающий глубину изображения.',
    size: '6.5 см',
    material: 'Акрил, ювелирная эпоксидная смола, серебристый карабин',
    features: ['Мягкая выпуклая капля смолы', 'Вкрапления мерцающих микроблесток', 'Прочный карабин с вертлюгом', 'Подарочный крафтовый пакетик'],
  },
  {
    id: 'fraiters-stickers-vinyl',
    name: 'Стикерпак А5 «Red Void Edition»',
    category: 'stickers',
    categoryName: 'Стикерпак',
    price: 350,
    inStock: true,
    stockCount: 35,
    badge: 'Бестселлер',
    image: 'https://images.unsplash.com/photo-1572375992501-4b0892d50c69?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-red-950 via-zinc-950 to-black',
    description: 'Набор из 14 виниловых стикеров с контурной плоттерной резкой. Влагозащитные, не выгорают на солнце, легко отклеиваются без следов клея.',
    size: 'Лист формата А5 (148 x 210 мм)',
    material: 'Плотный белый винил с матовой soft-touch ламинацией',
    features: ['14 наклеек на листе', 'Влагостойкие — подходят для ноутбуков и бутылок', 'Матовое приятное покрытие', 'Плоттерная высечка каждого стикера'],
  },
  {
    id: 'fraiters-stickers-holo-pack',
    name: 'Мини-пак стикеров «Glitch Noir»',
    category: 'stickers',
    categoryName: 'Стикерпак',
    price: 290,
    inStock: true,
    stockCount: 22,
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-neutral-900 via-red-950 to-neutral-950',
    description: '6 крупных одиночных стикеров на голографической основе. Каждый стикер упакован в индивидуальный пакетик с хедером.',
    size: 'Размер стикеров от 6 до 9 см',
    material: 'Голографический винил высокой плотности',
    features: ['6 уникальных стикеров', 'Переливающийся металлический блеск', 'Усиленный клеевой слой', 'Стойкость к ультрафиолету'],
  },
  {
    id: 'fraiters-pin-enamel-metal',
    name: 'Металлический пин «Cyber Fang»',
    category: 'pins',
    categoryName: 'Пин / Значок',
    price: 550,
    inStock: true,
    stockCount: 15,
    badge: 'Твердая эмаль',
    image: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-zinc-900 via-red-950 to-black',
    description: 'Премиальный значок из цинкового сплава с твердой эмалью (hard enamel). Золотое гальваническое покрытие и два резиновых замочка сзади.',
    size: '38 x 32 мм, толщина 2 мм',
    material: 'Металл (цинковый сплав), твердая цветная эмаль, золочение',
    features: ['Гладкая зеркальная полировка вровень с металлом', 'Два штифта для надежной фиксации (не прокручивается)', 'Резиновые заглушки-бабочки', 'Фирменная дизайнерская подложка'],
  },
  {
    id: 'fraiters-pin-acrylic-badge',
    name: 'Сет закатных значков (3 шт) «Fraiters Core»',
    category: 'pins',
    categoryName: 'Сет значков',
    price: 320,
    oldPrice: 390,
    inStock: true,
    stockCount: 28,
    image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-red-900 via-neutral-950 to-black',
    description: 'Набор из 3 металлических закатных значков с матовой ламинацией и надежной евробулавкой. Диаметр 44 мм.',
    size: 'Диаметр 44 мм каждого значка',
    material: 'Металлическая основа, лавсановая матовая пленка',
    features: ['3 штуки в наборе', 'Тактильное матовое покрытие', 'Усиленная стальная булавка', 'Планшетка с артом'],
  },
  {
    id: 'fraiters-hoodie-oversize',
    name: 'Худи оверсайз «Fraiters Vanguard» (Black/Red)',
    category: 'apparel',
    categoryName: 'Одежда',
    price: 4900,
    oldPrice: 5500,
    inStock: true,
    stockCount: 6,
    badge: 'Дроп ограничен',
    image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-neutral-900 via-red-950 to-black',
    description: 'Плотное оверсайз худи из футера 3-нитки с начесом. Шелкографическая печать на спине и вышивка на груди. Глубокий капюшон.',
    size: 'Размеры: S-M, L-XL (свободный оверсайз крой)',
    material: '100% плотный хлопок (футер пенье 380 г/м²)',
    features: ['Премиальный футер без скатывания', 'Стойкая трафаретная шелкография', 'Вышитый логотип на груди', 'Широкие манжеты и удобный карман'],
  },
  {
    id: 'fraiters-art-prints-set',
    name: 'Комплект арт-открыток «Crimson Horizon» (6 шт)',
    category: 'prints',
    categoryName: 'Открытки',
    price: 400,
    inStock: true,
    stockCount: 40,
    badge: 'Софт-тач',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800&auto=format&fit=crop&q=80',
    fallbackGradient: 'from-red-950 via-stone-900 to-black',
    description: 'Набор коллекционных почтовых карточек формата А6. Бархатистая ламинация Soft Touch и выборочный лак на ключевых деталях.',
    size: 'Формат А6 (105 x 148 мм), 6 открыток',
    material: 'Дизайнерский картон 350 г/м², Soft Touch ламинация, УФ-лак',
    features: ['6 уникальных иллюстраций', 'Приятная бархатная поверхность', 'Оборотная сторона расчерчена под почтовую марку', 'Подарочный сургучный конверт'],
  },
];

export const SHELF_LOCATIONS: ShelfLocation[] = [
  {
    id: 'shelf-msk-1',
    city: 'Москва',
    storeName: '«Твоя Полка» на Китай-Городе',
    address: 'ул. Маросейка, д. 6-8, стр. 1 (вход со двора)',
    metro: 'м. Китай-город (2 мин пешком)',
    shelfNumber: 'Полка № 42 (средний ярус)',
    workingHours: 'Ежедневно с 11:00 до 21:00',
    statusText: 'Пополнение мерча: 28 сентября',
    itemsAvailable: ['Акриловые стенды', 'Брелоки', 'Стикерпаки', 'Открытки'],
    yandexMapUrl: 'https://yandex.ru/maps/?text=Твоя+Полка+Маросейка+6-8',
  },
  {
    id: 'shelf-spb-1',
    city: 'Санкт-Петербург',
    storeName: '«Полка Чудес» в Севкабель Порту',
    address: 'Кожевенная линия, д. 40, Главное здание, 2 этаж',
    metro: 'м. Приморская / Василеостровская',
    shelfNumber: 'Полка № B-14',
    workingHours: 'Пн-Вс с 12:00 до 22:00',
    statusText: 'В наличии все стенды и новинки',
    itemsAvailable: ['Диорамы', 'Стенды', 'Голографические брелоки', 'Пины'],
    yandexMapUrl: 'https://yandex.ru/maps/?text=Полка+Чудес+Севкабель+Порт',
  },
  {
    id: 'shelf-ekb-1',
    city: 'Екатеринбург',
    storeName: 'Магазин «Craft Corner»',
    address: 'ул. Вайнера, д. 10, ТЦ «Успенский», 3 этаж',
    metro: 'м. Площадь 1905 года',
    shelfNumber: 'Полка № 8',
    workingHours: 'Ежедневно с 10:00 до 21:00',
    statusText: 'Осталось несколько стендов и стикеры',
    itemsAvailable: ['Стикерпаки', 'Значки', 'Брелоки'],
    yandexMapUrl: 'https://yandex.ru/maps/?text=Вайнера+10+Екатеринбург',
  },
  {
    id: 'shelf-kzn-1',
    city: 'Казань',
    storeName: 'Арт-пространство «КрафтЛавка»',
    address: 'ул. Баумана, д. 29, арка во двор',
    metro: 'м. Кремлёвская',
    shelfNumber: 'Полка № 19',
    workingHours: 'Ежедневно с 11:00 до 20:00',
    statusText: 'Свежий завоз от 25 сентября',
    itemsAvailable: ['Стенды', 'Стикеры', 'Открытки', 'Брелоки'],
    yandexMapUrl: 'https://yandex.ru/maps/?text=Казань+Баумана+29',
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Алина K.',
    handle: '@alina_darkart',
    date: 'Вчера в 17:40',
    rating: 5,
    text: 'Заказывала акриловый стенд Crimson и набор открыток. Упаковка просто космос — толстенный слой пупырки, плотный картон, дошло в идеале! Печать очень сочная, акрил прозрачный как стекло. Отдельное спасибо за подарочные стикеры в конверте!',
    productName: 'Акриловый стенд «Crimson Requiem»',
    verified: true,
    avatarBg: 'bg-red-900',
  },
  {
    id: 'rev-2',
    author: 'Максим В.',
    handle: '@max_frait_fan',
    date: '26 сентября',
    rating: 5,
    text: 'Забирал на полочке на Китай-городе. Вживую стенды выглядят еще круче, чем на фотках в тгк! Голографический брелок переливается безумно красиво на солнце. Сразу повесил на ключи. Жду следующий дроп одежды!',
    productName: 'Голографический брелок «Abyss Walker»',
    verified: true,
    avatarBg: 'bg-neutral-800',
  },
  {
    id: 'rev-3',
    author: 'София (Sofi)',
    handle: '@sofi_sketch',
    date: '21 сентября',
    rating: 5,
    text: 'Брала худи оверсайз. Ткань тяжелая, плотная, внутри мягкий приятный начес. Принт после 4 стирок вообще не потрескался! Размер сел свободно, как надо. Fraiters держит планку, рекомендую всем!',
    productName: 'Худи оверсайз «Fraiters Vanguard»',
    verified: true,
    avatarBg: 'bg-red-950',
  },
  {
    id: 'rev-4',
    author: 'Дмитрий',
    handle: '@dmitry_v',
    date: '18 сентября',
    rating: 5,
    text: 'Доставка СДЭКом в Новосибирск доехала за 3 дня. Диорама собирается плотно, в пазах не шатается. Настоящее украшение для рабочего стола. Трек скинули в телеграмме сразу после отправки.',
    productName: 'Диорама «Shadow Protocol»',
    verified: true,
    avatarBg: 'bg-rose-950',
  },
];

export const FAQ_LIST: FaqItem[] = [
  {
    id: 'faq-1',
    question: 'Как быстро отправляется заказ после оформления?',
    answer: 'Товары из наличия бережно собираются и передаются в службу доставки (Почта РФ / СДЭК) в течение 1–3 рабочих дней. Сразу после отправки мы присылаем вам трек-номер для отслеживания в Telegram или SMS.',
  },
  {
    id: 'faq-2',
    question: 'Как защищены товары при доставке?',
    answer: 'Каждый акриловый стенд и брелок покрыт защитной пленкой с двух сторон. Заказ упаковывается в пузырчатую пленку (bubble wrap) в несколько слоев, прокладывается жестким крафтовым картоном и помещается в ударопрочный курьер-пакет или коробку.',
  },
  {
    id: 'faq-3',
    question: 'Что такое «Полочки» и можно ли купить мерч вживую?',
    answer: 'Полочки — это партнерские витрины в магазинах крафта и комиксов в Москве, Санкт-Петербурге, Екатеринбурге и Казани. Вы можете прийти в магазин в рабочие часы, посмотреть мерч вживую и сразу купить его на кассе магазина без ожидания доставки.',
  },
  {
    id: 'faq-4',
    question: 'Доставляете ли вы в Беларусь, Казахстан и другие страны?',
    answer: 'Да! Доставка в Беларусь и Казахстан осуществляется СДЭКом или Почтой. При оформлении заказа укажите вашу страну и город в комментарии, и мы рассчитаем точную стоимость доставки по тарифам службы.',
  },
  {
    id: 'faq-5',
    question: 'Стенд выглядит мутным или с царапинами — что делать?',
    answer: 'Не переживайте! Все акриловые изделия оклеены матовой защитной транспортировочной пленкой с лицевой и оборотной стороны. Просто аккуратно подцепите краешек ногтем или зубочисткой и снимите пленку — под ней идеальный кристальный глянцевый акрил!',
  },
  {
    id: 'faq-6',
    question: 'Как связаться с автором или заказать оптовую партию?',
    answer: 'Наш официальный Telegram-канал: https://t.me/fraiters. По всем вопросам, коллаборациям или индивидуальным заказам вы можете написать напрямую в ЛС администратору паблика.',
  },
];

export const INITIAL_ORDERS: OrderRecord[] = [
  {
    id: 'FR-948201',
    date: '4 октября, 11:25',
    status: 'new',
    total: 2840,
    values: {
      fullName: 'Анастасия Воронова',
      telegramUsername: '@nastyavrn',
      phone: '+7 (916) 432-88-12',
      city: 'Москва',
      address: 'ПВЗ СДЭК ул. Тверская 14',
      postalCode: '125009',
      deliveryMethod: 'cdek',
      paymentMethod: 'card',
      comment: 'Положите, пожалуйста, больше красных стикеров в подарок!',
    },
    items: [
      { product: PRODUCTS[0], quantity: 2 }, // Crimson Requiem stand
      { product: PRODUCTS[2], quantity: 1 }, // Abyss Walker charm
      { product: PRODUCTS[3], quantity: 1 }, // Stickerpack
    ],
  },
  {
    id: 'FR-883192',
    date: '3 октября, 18:40',
    status: 'processing',
    total: 5120,
    values: {
      fullName: 'Михаил Соколов',
      telegramUsername: '@misha_sklv',
      phone: '+7 (921) 775-31-09',
      city: 'Санкт-Петербург',
      address: 'Лиговский пр-т 48, кв 12',
      postalCode: '191040',
      deliveryMethod: 'cdek',
      paymentMethod: 'sbp',
    },
    items: [
      { product: PRODUCTS[5], quantity: 1 }, // Hoodie
      { product: PRODUCTS[1], quantity: 1 }, // Diorama Shadow Protocol
    ],
  },
  {
    id: 'FR-812044',
    date: '3 октября, 14:15',
    status: 'shipped',
    total: 1690,
    values: {
      fullName: 'Дарья Романова',
      telegramUsername: '@dasharoma',
      phone: '+7 (903) 112-99-44',
      city: 'Екатеринбург',
      address: 'ул. Малышева 28',
      postalCode: '620014',
      deliveryMethod: 'post',
      paymentMethod: 'card',
    },
    items: [
      { product: PRODUCTS[1], quantity: 1 }, // Diorama Shadow Protocol
      { product: PRODUCTS[4], quantity: 1 }, // Pin set
    ],
  },
  {
    id: 'FR-776102',
    date: '2 октября, 19:50',
    status: 'completed',
    total: 2240,
    values: {
      fullName: 'Артем Казанцев',
      telegramUsername: '@artem_kzn',
      phone: '+7 (987) 654-32-10',
      city: 'Казань',
      address: 'ул. Баумана, д. 22',
      postalCode: '420111',
      deliveryMethod: 'shelf',
      paymentMethod: 'card',
    },
    items: [
      { product: PRODUCTS[0], quantity: 1 }, // Stand
      { product: PRODUCTS[6], quantity: 1 }, // Print pack
      { product: PRODUCTS[2], quantity: 2 }, // Charms
    ],
  },
  {
    id: 'FR-720193',
    date: '2 октября, 10:20',
    status: 'completed',
    total: 1300,
    values: {
      fullName: 'Екатерина Морозова',
      telegramUsername: '@katyamrz',
      phone: '+7 (999) 812-70-65',
      city: 'Новосибирск',
      address: 'Красный проспект 15',
      postalCode: '630099',
      deliveryMethod: 'cdek',
      paymentMethod: 'sbp',
    },
    items: [
      { product: PRODUCTS[2], quantity: 1 }, // Charm
      { product: PRODUCTS[3], quantity: 2 }, // Stickerpacks
    ],
  },
  {
    id: 'FR-689304',
    date: '1 октября, 16:30',
    status: 'completed',
    total: 4890,
    values: {
      fullName: 'Владислав Ли',
      telegramUsername: '@vlad_lee',
      phone: '+7 (905) 555-12-89',
      city: 'Москва',
      address: 'Ленинский проспект 45',
      postalCode: '119334',
      deliveryMethod: 'cdek',
      paymentMethod: 'card',
    },
    items: [
      { product: PRODUCTS[5], quantity: 1 }, // Hoodie
      { product: PRODUCTS[0], quantity: 1 }, // Stand
    ],
  },
  {
    id: 'FR-610294',
    date: '30 сентября, 13:10',
    status: 'completed',
    total: 1740,
    values: {
      fullName: 'Полина Смирнова',
      telegramUsername: '@polina_smr',
      phone: '+7 (911) 203-49-11',
      city: 'Санкт-Петербург',
      address: 'Полочка «Полка Чудес»',
      postalCode: '190000',
      deliveryMethod: 'shelf',
      paymentMethod: 'card',
    },
    items: [
      { product: PRODUCTS[0], quantity: 1 }, // Stand
      { product: PRODUCTS[2], quantity: 1 }, // Charm
      { product: PRODUCTS[4], quantity: 1 }, // Pins
    ],
  },
  {
    id: 'FR-592019',
    date: '29 сентября, 17:45',
    status: 'completed',
    total: 950,
    values: {
      fullName: 'Иван Кузнецов',
      telegramUsername: '@ivan_kuzn',
      phone: '+7 (926) 304-12-78',
      city: 'Нижний Новгород',
      address: 'ул. Белинского 32',
      postalCode: '603000',
      deliveryMethod: 'post',
      paymentMethod: 'card',
    },
    items: [
      { product: PRODUCTS[0], quantity: 1 }, // Stand
    ],
  },
];
